### PR TITLE
Major fixing

### PR DESCRIPTION
**Pull request by metagn**
;)

### CODE REVIEW

**Comment by elifoster** [comment]
The addOreSpawn refactor is kind of pointless. In case you want to generate in different worlds and or with different blocks, you'll want to use the method that already exists and undo what you (hlaaftana) refactored it to be.

**Comment by metagn** [comment]
I added in another method for it, did you not see it? http://i.imgur.com/y0ELOL2.png

**Comment by elifoster** [comment]
(For the sake of this post, addOreSpawn1 is considered to be addOreSpawn(block, metadata, world, random, blockXPos, blockZPos, maxX, maxZ, maxVeinSize, chancesToSpawn, minY, maxY), and addOreSpawn2 is considered to be addOreSpawn(block, metadata, target, world, random, blockXPos, blockZPos, maxX, maxZ, maxVeinSize, chancesToSpawn, minY, maxY))

I did see it, that's my issue. There's no point for addOreSpawn1 to even exist because all it does is call the other addOreSpawn method.

I'll try to explain it better. You are using your addOreSpawn1 for all generation of ores. The problem creeps in when you decide "Hey, I want some nether and end ores", because that method, which generateSurface is using, calls addOreSpawn2 with target being Blocks.stone. You'd need to either call the addOreSpawn2 method, or create a new method nearly identical to addOreSpawn1 with the only difference being the target parameter in the addOreSpawn2 calls. You are much better off just getting rid of addOreSpawn1 and replacing all addOreSpawn1 uses with addOreSpawn2.

An even better method would be to make an array of all the ores, and use a for loop (for block : gemOreArray) and just call addOreSpawn2 with the block parameter being the block defined by the loop definition.

**Comment by elifoster** [comment]
My first solution (second one not so much, because of loops and iterating through arrays) would also increase performance, because it wouldn't be "jumping around" these methods. It would also completely eliminate the possibility of a StackOverFlow (which would be unlikely anyway, but still).

**Comment by Reignofmagic** [comment]
So correct me if I'm wrong in my understanding here.

The Method that hlaaftana added at the bottom of the ReignWorldGen was not necessary because it was already done in my previous version of the code. It just simply shortened the code for each specific ore slightly. 

What you are saying is that it is not necessary, because all it does is reference the previous/forge default method. The problem creeps up when you are trying to either generate ores in another dimension, or in another block that isn't directly coded into the addOreSpawn method, thus needing a nearly identical set of code for the new block the ores are replacing.

So my question for the both of you is, wouldn't it be simpler/more flexible... if slightly longer code wise to revert to the previous method I was using which called the block that each ore could replace? Or did I miss both elifoster's point and hlaaftana's intent?

Thanks for the clarification!

**Comment by elifoster** [comment]
@Reignofmagic Your original code is better, that was my main point. My other, less important, point was that it could be improved (for readability and quicker dev time, not necessarily by performance, but it really shouldn't take that big of a performance toll) by using a for loop and an array of gemOres. I will get a PR set up for this to better explain what I mean.

**Pull request merged**
